### ISSUE TITLE
[1.18.2 Fabric] Crash rendering cave spider in spawner

### ISSUE THREAD

**Issue by Alexander3847575** [Pedro270707/headed#6]
Flying around world in creative when presumably a spawner generated and the world crashed. Could possibly be due to an incompatibility. 

https://mclo.gs/8pNb7CE

Took a peek at the code and it might this BlockItem cast (actually on line 64):
`if (item instanceof BlockItem && ((BlockItem)item).getBlock() instanceof AbstractHeadedSkullBlock)`

**Comment by suerion** [comment]
I had looked on the Log, You had Dungeon Arise in your modpack, could be, thad the spawner is from dungeon Arise?

the error is the same as for me on 1.19.2 https://github.com/Pedro270707/headed/issues/7
